// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.6.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ModuleNode> dco_decode_list_module_node(dynamic raw);

  @protected
  Uint64List dco_decode_list_prim_u_64_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SignalInfo> dco_decode_list_signal_info(dynamic raw);

  @protected
  List<SignalWaveformData> dco_decode_list_signal_waveform_data(dynamic raw);

  @protected
  List<WaveformDataPoint> dco_decode_list_waveform_data_point(dynamic raw);

  @protected
  ModuleNode dco_decode_module_node(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  SignalInfo dco_decode_signal_info(dynamic raw);

  @protected
  SignalWaveformData dco_decode_signal_waveform_data(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  WaveformDataPoint dco_decode_waveform_data_point(dynamic raw);

  @protected
  WaveformMetadata dco_decode_waveform_metadata(dynamic raw);

  @protected
  WaveformStructure dco_decode_waveform_structure(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ModuleNode> sse_decode_list_module_node(SseDeserializer deserializer);

  @protected
  Uint64List sse_decode_list_prim_u_64_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SignalInfo> sse_decode_list_signal_info(SseDeserializer deserializer);

  @protected
  List<SignalWaveformData> sse_decode_list_signal_waveform_data(
      SseDeserializer deserializer);

  @protected
  List<WaveformDataPoint> sse_decode_list_waveform_data_point(
      SseDeserializer deserializer);

  @protected
  ModuleNode sse_decode_module_node(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  SignalInfo sse_decode_signal_info(SseDeserializer deserializer);

  @protected
  SignalWaveformData sse_decode_signal_waveform_data(
      SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  WaveformDataPoint sse_decode_waveform_data_point(
      SseDeserializer deserializer);

  @protected
  WaveformMetadata sse_decode_waveform_metadata(SseDeserializer deserializer);

  @protected
  WaveformStructure sse_decode_waveform_structure(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_prim_u_8_strict(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<ffi.Uint64> cst_encode_box_autoadd_u_64(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_u_64(cst_encode_u_64(raw));
  }

  @protected
  ffi.Pointer<wire_cst_list_String> cst_encode_list_String(List<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_String(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      ans.ref.ptr[i] = cst_encode_String(raw[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_module_node> cst_encode_list_module_node(
      List<ModuleNode> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_module_node(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_module_node(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_64_strict> cst_encode_list_prim_u_64_strict(
      Uint64List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_64_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw.inner);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_loose> cst_encode_list_prim_u_8_loose(
      List<int> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_loose(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_list_prim_u_8_strict(
      Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_signal_info> cst_encode_list_signal_info(
      List<SignalInfo> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_signal_info(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_signal_info(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_signal_waveform_data>
      cst_encode_list_signal_waveform_data(List<SignalWaveformData> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_signal_waveform_data(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_signal_waveform_data(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_waveform_data_point>
      cst_encode_list_waveform_data_point(List<WaveformDataPoint> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_waveform_data_point(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_waveform_data_point(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_opt_String(
      String? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_String(raw);
  }

  @protected
  ffi.Pointer<ffi.Uint64> cst_encode_opt_box_autoadd_u_64(BigInt? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_u_64(raw);
  }

  @protected
  int cst_encode_u_64(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toSigned(64).toInt();
  }

  @protected
  void cst_api_fill_to_wire_module_node(
      ModuleNode apiObj, wire_cst_module_node wireObj) {
    wireObj.name = cst_encode_String(apiObj.name);
    wireObj.full_path = cst_encode_String(apiObj.fullPath);
    wireObj.scope_type = cst_encode_String(apiObj.scopeType);
    wireObj.signals = cst_encode_list_signal_info(apiObj.signals);
    wireObj.sub_modules = cst_encode_list_module_node(apiObj.subModules);
  }

  @protected
  void cst_api_fill_to_wire_signal_info(
      SignalInfo apiObj, wire_cst_signal_info wireObj) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.name = cst_encode_String(apiObj.name);
    wireObj.full_path = cst_encode_String(apiObj.fullPath);
    wireObj.signal_type = cst_encode_String(apiObj.signalType);
    wireObj.bit_width = cst_encode_u_32(apiObj.bitWidth);
    wireObj.scope_id = cst_encode_u_64(apiObj.scopeId);
  }

  @protected
  void cst_api_fill_to_wire_signal_waveform_data(
      SignalWaveformData apiObj, wire_cst_signal_waveform_data wireObj) {
    wireObj.signal_id = cst_encode_String(apiObj.signalId);
    wireObj.data = cst_encode_list_waveform_data_point(apiObj.data);
  }

  @protected
  void cst_api_fill_to_wire_waveform_data_point(
      WaveformDataPoint apiObj, wire_cst_waveform_data_point wireObj) {
    wireObj.time = cst_encode_u_64(apiObj.time);
    wireObj.value = cst_encode_String(apiObj.value);
  }

  @protected
  void cst_api_fill_to_wire_waveform_metadata(
      WaveformMetadata apiObj, wire_cst_waveform_metadata wireObj) {
    wireObj.source = cst_encode_String(apiObj.source);
    wireObj.timescale = cst_encode_String(apiObj.timescale);
    wireObj.timescale_factor = cst_encode_u_32(apiObj.timescaleFactor);
    wireObj.date = cst_encode_opt_String(apiObj.date);
    wireObj.version = cst_encode_opt_String(apiObj.version);
    wireObj.format = cst_encode_String(apiObj.format);
    wireObj.start_time = cst_encode_u_64(apiObj.startTime);
    wireObj.end_time = cst_encode_u_64(apiObj.endTime);
  }

  @protected
  void cst_api_fill_to_wire_waveform_structure(
      WaveformStructure apiObj, wire_cst_waveform_structure wireObj) {
    cst_api_fill_to_wire_waveform_metadata(apiObj.metadata, wireObj.metadata);
    wireObj.modules = cst_encode_list_module_node(apiObj.modules);
    wireObj.all_signal_ids = cst_encode_list_String(apiObj.allSignalIds);
  }

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  int cst_encode_u_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_module_node(
      List<ModuleNode> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_64_strict(
      Uint64List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_signal_info(
      List<SignalInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_signal_waveform_data(
      List<SignalWaveformData> self, SseSerializer serializer);

  @protected
  void sse_encode_list_waveform_data_point(
      List<WaveformDataPoint> self, SseSerializer serializer);

  @protected
  void sse_encode_module_node(ModuleNode self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_signal_info(SignalInfo self, SseSerializer serializer);

  @protected
  void sse_encode_signal_waveform_data(
      SignalWaveformData self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_waveform_data_point(
      WaveformDataPoint self, SseSerializer serializer);

  @protected
  void sse_encode_waveform_metadata(
      WaveformMetadata self, SseSerializer serializer);

  @protected
  void sse_encode_waveform_structure(
      WaveformStructure self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

/// generated by flutter_rust_bridge
class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RustLibWire.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void store_dart_post_cobject(
    DartPostCObjectFnType ptr,
  ) {
    return _store_dart_post_cobject(
      ptr,
    );
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
          'store_dart_post_cobject');
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  void wire__crate__api__get_all_timestamps(
    int port_,
  ) {
    return _wire__crate__api__get_all_timestamps(
      port_,
    );
  }

  late final _wire__crate__api__get_all_timestampsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'frbgen_rohd_wellen_wire__crate__api__get_all_timestamps');
  late final _wire__crate__api__get_all_timestamps =
      _wire__crate__api__get_all_timestampsPtr.asFunction<void Function(int)>();

  void wire__crate__api__get_max_timestamp(
    int port_,
  ) {
    return _wire__crate__api__get_max_timestamp(
      port_,
    );
  }

  late final _wire__crate__api__get_max_timestampPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'frbgen_rohd_wellen_wire__crate__api__get_max_timestamp');
  late final _wire__crate__api__get_max_timestamp =
      _wire__crate__api__get_max_timestampPtr.asFunction<void Function(int)>();

  void wire__crate__api__get_waveform_data(
    int port_,
    ffi.Pointer<wire_cst_list_String> signal_ids,
    ffi.Pointer<ffi.Uint64> start_time,
    ffi.Pointer<ffi.Uint64> end_time,
  ) {
    return _wire__crate__api__get_waveform_data(
      port_,
      signal_ids,
      start_time,
      end_time,
    );
  }

  late final _wire__crate__api__get_waveform_dataPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Int64, ffi.Pointer<wire_cst_list_String>,
                  ffi.Pointer<ffi.Uint64>, ffi.Pointer<ffi.Uint64>)>>(
      'frbgen_rohd_wellen_wire__crate__api__get_waveform_data');
  late final _wire__crate__api__get_waveform_data =
      _wire__crate__api__get_waveform_dataPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_String>,
              ffi.Pointer<ffi.Uint64>, ffi.Pointer<ffi.Uint64>)>();

  void wire__crate__api__get_waveform_structure(
    int port_,
  ) {
    return _wire__crate__api__get_waveform_structure(
      port_,
    );
  }

  late final _wire__crate__api__get_waveform_structurePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'frbgen_rohd_wellen_wire__crate__api__get_waveform_structure');
  late final _wire__crate__api__get_waveform_structure =
      _wire__crate__api__get_waveform_structurePtr
          .asFunction<void Function(int)>();

  void wire__crate__api__is_waveform_loaded(
    int port_,
  ) {
    return _wire__crate__api__is_waveform_loaded(
      port_,
    );
  }

  late final _wire__crate__api__is_waveform_loadedPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'frbgen_rohd_wellen_wire__crate__api__is_waveform_loaded');
  late final _wire__crate__api__is_waveform_loaded =
      _wire__crate__api__is_waveform_loadedPtr.asFunction<void Function(int)>();

  void wire__crate__api__load_waveform(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> file_path,
  ) {
    return _wire__crate__api__load_waveform(
      port_,
      file_path,
    );
  }

  late final _wire__crate__api__load_waveformPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_rohd_wellen_wire__crate__api__load_waveform');
  late final _wire__crate__api__load_waveform =
      _wire__crate__api__load_waveformPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__load_waveform_from_bytes(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> bytes,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> file_name,
  ) {
    return _wire__crate__api__load_waveform_from_bytes(
      port_,
      bytes,
      file_name,
    );
  }

  late final _wire__crate__api__load_waveform_from_bytesPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64,
                  ffi.Pointer<wire_cst_list_prim_u_8_loose>,
                  ffi.Pointer<wire_cst_list_prim_u_8_strict>)>>(
      'frbgen_rohd_wellen_wire__crate__api__load_waveform_from_bytes');
  late final _wire__crate__api__load_waveform_from_bytes =
      _wire__crate__api__load_waveform_from_bytesPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__unload_waveform(
    int port_,
  ) {
    return _wire__crate__api__unload_waveform(
      port_,
    );
  }

  late final _wire__crate__api__unload_waveformPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'frbgen_rohd_wellen_wire__crate__api__unload_waveform');
  late final _wire__crate__api__unload_waveform =
      _wire__crate__api__unload_waveformPtr.asFunction<void Function(int)>();

  ffi.Pointer<ffi.Uint64> cst_new_box_autoadd_u_64(
    int value,
  ) {
    return _cst_new_box_autoadd_u_64(
      value,
    );
  }

  late final _cst_new_box_autoadd_u_64Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Uint64> Function(ffi.Uint64)>>(
          'frbgen_rohd_wellen_cst_new_box_autoadd_u_64');
  late final _cst_new_box_autoadd_u_64 = _cst_new_box_autoadd_u_64Ptr
      .asFunction<ffi.Pointer<ffi.Uint64> Function(int)>();

  ffi.Pointer<wire_cst_list_String> cst_new_list_String(
    int len,
  ) {
    return _cst_new_list_String(
      len,
    );
  }

  late final _cst_new_list_StringPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_String> Function(
              ffi.Int32)>>('frbgen_rohd_wellen_cst_new_list_String');
  late final _cst_new_list_String = _cst_new_list_StringPtr
      .asFunction<ffi.Pointer<wire_cst_list_String> Function(int)>();

  ffi.Pointer<wire_cst_list_module_node> cst_new_list_module_node(
    int len,
  ) {
    return _cst_new_list_module_node(
      len,
    );
  }

  late final _cst_new_list_module_nodePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_module_node> Function(
              ffi.Int32)>>('frbgen_rohd_wellen_cst_new_list_module_node');
  late final _cst_new_list_module_node = _cst_new_list_module_nodePtr
      .asFunction<ffi.Pointer<wire_cst_list_module_node> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_64_strict> cst_new_list_prim_u_64_strict(
    int len,
  ) {
    return _cst_new_list_prim_u_64_strict(
      len,
    );
  }

  late final _cst_new_list_prim_u_64_strictPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_64_strict> Function(
              ffi.Int32)>>('frbgen_rohd_wellen_cst_new_list_prim_u_64_strict');
  late final _cst_new_list_prim_u_64_strict = _cst_new_list_prim_u_64_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_64_strict> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_loose> cst_new_list_prim_u_8_loose(
    int len,
  ) {
    return _cst_new_list_prim_u_8_loose(
      len,
    );
  }

  late final _cst_new_list_prim_u_8_loosePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_loose> Function(
              ffi.Int32)>>('frbgen_rohd_wellen_cst_new_list_prim_u_8_loose');
  late final _cst_new_list_prim_u_8_loose = _cst_new_list_prim_u_8_loosePtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_loose> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_new_list_prim_u_8_strict(
    int len,
  ) {
    return _cst_new_list_prim_u_8_strict(
      len,
    );
  }

  late final _cst_new_list_prim_u_8_strictPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(
              ffi.Int32)>>('frbgen_rohd_wellen_cst_new_list_prim_u_8_strict');
  late final _cst_new_list_prim_u_8_strict = _cst_new_list_prim_u_8_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(int)>();

  ffi.Pointer<wire_cst_list_signal_info> cst_new_list_signal_info(
    int len,
  ) {
    return _cst_new_list_signal_info(
      len,
    );
  }

  late final _cst_new_list_signal_infoPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_signal_info> Function(
              ffi.Int32)>>('frbgen_rohd_wellen_cst_new_list_signal_info');
  late final _cst_new_list_signal_info = _cst_new_list_signal_infoPtr
      .asFunction<ffi.Pointer<wire_cst_list_signal_info> Function(int)>();

  ffi.Pointer<wire_cst_list_signal_waveform_data>
      cst_new_list_signal_waveform_data(
    int len,
  ) {
    return _cst_new_list_signal_waveform_data(
      len,
    );
  }

  late final _cst_new_list_signal_waveform_dataPtr = _lookup<
          ffi.NativeFunction<
              ffi.Pointer<wire_cst_list_signal_waveform_data> Function(
                  ffi.Int32)>>(
      'frbgen_rohd_wellen_cst_new_list_signal_waveform_data');
  late final _cst_new_list_signal_waveform_data =
      _cst_new_list_signal_waveform_dataPtr.asFunction<
          ffi.Pointer<wire_cst_list_signal_waveform_data> Function(int)>();

  ffi.Pointer<wire_cst_list_waveform_data_point>
      cst_new_list_waveform_data_point(
    int len,
  ) {
    return _cst_new_list_waveform_data_point(
      len,
    );
  }

  late final _cst_new_list_waveform_data_pointPtr = _lookup<
          ffi.NativeFunction<
              ffi.Pointer<wire_cst_list_waveform_data_point> Function(
                  ffi.Int32)>>(
      'frbgen_rohd_wellen_cst_new_list_waveform_data_point');
  late final _cst_new_list_waveform_data_point =
      _cst_new_list_waveform_data_pointPtr.asFunction<
          ffi.Pointer<wire_cst_list_waveform_data_point> Function(int)>();

  int dummy_method_to_enforce_bundling() {
    return _dummy_method_to_enforce_bundling();
  }

  late final _dummy_method_to_enforce_bundlingPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
          'dummy_method_to_enforce_bundling');
  late final _dummy_method_to_enforce_bundling =
      _dummy_method_to_enforce_bundlingPtr.asFunction<int Function()>();
}

typedef DartPort = ffi.Int64;
typedef DartDartPort = int;
typedef DartPostCObjectFnTypeFunction = ffi.Bool Function(
    DartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartDartPostCObjectFnTypeFunction = bool Function(
    DartDartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartPostCObjectFnType
    = ffi.Pointer<ffi.NativeFunction<DartPostCObjectFnTypeFunction>>;

final class wire_cst_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_String extends ffi.Struct {
  external ffi.Pointer<ffi.Pointer<wire_cst_list_prim_u_8_strict>> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_prim_u_8_loose extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_signal_info extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> name;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> full_path;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> signal_type;

  @ffi.Uint32()
  external int bit_width;

  @ffi.Uint64()
  external int scope_id;
}

final class wire_cst_list_signal_info extends ffi.Struct {
  external ffi.Pointer<wire_cst_signal_info> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_module_node extends ffi.Struct {
  external ffi.Pointer<wire_cst_module_node> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_module_node extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> name;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> full_path;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> scope_type;

  external ffi.Pointer<wire_cst_list_signal_info> signals;

  external ffi.Pointer<wire_cst_list_module_node> sub_modules;
}

final class wire_cst_list_prim_u_64_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint64> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_waveform_data_point extends ffi.Struct {
  @ffi.Uint64()
  external int time;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> value;
}

final class wire_cst_list_waveform_data_point extends ffi.Struct {
  external ffi.Pointer<wire_cst_waveform_data_point> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_signal_waveform_data extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> signal_id;

  external ffi.Pointer<wire_cst_list_waveform_data_point> data;
}

final class wire_cst_list_signal_waveform_data extends ffi.Struct {
  external ffi.Pointer<wire_cst_signal_waveform_data> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_waveform_metadata extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> source;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> timescale;

  @ffi.Uint32()
  external int timescale_factor;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> date;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> version;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> format;

  @ffi.Uint64()
  external int start_time;

  @ffi.Uint64()
  external int end_time;
}

final class wire_cst_waveform_structure extends ffi.Struct {
  external wire_cst_waveform_metadata metadata;

  external ffi.Pointer<wire_cst_list_module_node> modules;

  external ffi.Pointer<wire_cst_list_String> all_signal_ids;
}
