// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.6.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ModuleNode> dco_decode_list_module_node(dynamic raw);

  @protected
  Uint64List dco_decode_list_prim_u_64_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SignalInfo> dco_decode_list_signal_info(dynamic raw);

  @protected
  List<SignalWaveformData> dco_decode_list_signal_waveform_data(dynamic raw);

  @protected
  List<WaveformDataPoint> dco_decode_list_waveform_data_point(dynamic raw);

  @protected
  ModuleNode dco_decode_module_node(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  SignalInfo dco_decode_signal_info(dynamic raw);

  @protected
  SignalWaveformData dco_decode_signal_waveform_data(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  WaveformDataPoint dco_decode_waveform_data_point(dynamic raw);

  @protected
  WaveformMetadata dco_decode_waveform_metadata(dynamic raw);

  @protected
  WaveformStructure dco_decode_waveform_structure(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ModuleNode> sse_decode_list_module_node(SseDeserializer deserializer);

  @protected
  Uint64List sse_decode_list_prim_u_64_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SignalInfo> sse_decode_list_signal_info(SseDeserializer deserializer);

  @protected
  List<SignalWaveformData> sse_decode_list_signal_waveform_data(
      SseDeserializer deserializer);

  @protected
  List<WaveformDataPoint> sse_decode_list_waveform_data_point(
      SseDeserializer deserializer);

  @protected
  ModuleNode sse_decode_module_node(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  SignalInfo sse_decode_signal_info(SseDeserializer deserializer);

  @protected
  SignalWaveformData sse_decode_signal_waveform_data(
      SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  WaveformDataPoint sse_decode_waveform_data_point(
      SseDeserializer deserializer);

  @protected
  WaveformMetadata sse_decode_waveform_metadata(SseDeserializer deserializer);

  @protected
  WaveformStructure sse_decode_waveform_structure(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  String cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  JSAny cst_encode_box_autoadd_u_64(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_u_64(raw);
  }

  @protected
  JSAny cst_encode_list_String(List<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_String).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_module_node(List<ModuleNode> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_module_node).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_64_strict(Uint64List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.inner.jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_8_loose(List<int> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_8_strict(Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_list_signal_info(List<SignalInfo> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_signal_info).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_signal_waveform_data(List<SignalWaveformData> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_signal_waveform_data).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_waveform_data_point(List<WaveformDataPoint> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_waveform_data_point).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_module_node(ModuleNode raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.name),
      cst_encode_String(raw.fullPath),
      cst_encode_String(raw.scopeType),
      cst_encode_list_signal_info(raw.signals),
      cst_encode_list_module_node(raw.subModules)
    ].jsify()!;
  }

  @protected
  String? cst_encode_opt_String(String? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_String(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_u_64(BigInt? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_u_64(raw);
  }

  @protected
  JSAny cst_encode_signal_info(SignalInfo raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.id),
      cst_encode_String(raw.name),
      cst_encode_String(raw.fullPath),
      cst_encode_String(raw.signalType),
      cst_encode_u_32(raw.bitWidth),
      cst_encode_u_64(raw.scopeId)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_signal_waveform_data(SignalWaveformData raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.signalId),
      cst_encode_list_waveform_data_point(raw.data)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_u_64(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  JSAny cst_encode_waveform_data_point(WaveformDataPoint raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [cst_encode_u_64(raw.time), cst_encode_String(raw.value)].jsify()!;
  }

  @protected
  JSAny cst_encode_waveform_metadata(WaveformMetadata raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.source),
      cst_encode_String(raw.timescale),
      cst_encode_u_32(raw.timescaleFactor),
      cst_encode_opt_String(raw.date),
      cst_encode_opt_String(raw.version),
      cst_encode_String(raw.format),
      cst_encode_u_64(raw.startTime),
      cst_encode_u_64(raw.endTime)
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_waveform_structure(WaveformStructure raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_waveform_metadata(raw.metadata),
      cst_encode_list_module_node(raw.modules),
      cst_encode_list_String(raw.allSignalIds)
    ].jsify()!;
  }

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  int cst_encode_u_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_module_node(
      List<ModuleNode> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_64_strict(
      Uint64List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_signal_info(
      List<SignalInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_signal_waveform_data(
      List<SignalWaveformData> self, SseSerializer serializer);

  @protected
  void sse_encode_list_waveform_data_point(
      List<WaveformDataPoint> self, SseSerializer serializer);

  @protected
  void sse_encode_module_node(ModuleNode self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_signal_info(SignalInfo self, SseSerializer serializer);

  @protected
  void sse_encode_signal_waveform_data(
      SignalWaveformData self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_waveform_data_point(
      WaveformDataPoint self, SseSerializer serializer);

  @protected
  void sse_encode_waveform_metadata(
      WaveformMetadata self, SseSerializer serializer);

  @protected
  void sse_encode_waveform_structure(
      WaveformStructure self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void wire__crate__api__get_all_timestamps(NativePortType port_) =>
      wasmModule.wire__crate__api__get_all_timestamps(port_);

  void wire__crate__api__get_max_timestamp(NativePortType port_) =>
      wasmModule.wire__crate__api__get_max_timestamp(port_);

  void wire__crate__api__get_waveform_data(NativePortType port_,
          JSAny signal_ids, JSAny? start_time, JSAny? end_time) =>
      wasmModule.wire__crate__api__get_waveform_data(
          port_, signal_ids, start_time, end_time);

  void wire__crate__api__get_waveform_structure(NativePortType port_) =>
      wasmModule.wire__crate__api__get_waveform_structure(port_);

  void wire__crate__api__is_waveform_loaded(NativePortType port_) =>
      wasmModule.wire__crate__api__is_waveform_loaded(port_);

  void wire__crate__api__load_waveform(
          NativePortType port_, String file_path) =>
      wasmModule.wire__crate__api__load_waveform(port_, file_path);

  void wire__crate__api__load_waveform_from_bytes(
          NativePortType port_, JSAny bytes, String? file_name) =>
      wasmModule.wire__crate__api__load_waveform_from_bytes(
          port_, bytes, file_name);

  void wire__crate__api__unload_waveform(NativePortType port_) =>
      wasmModule.wire__crate__api__unload_waveform(port_);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void wire__crate__api__get_all_timestamps(NativePortType port_);

  external void wire__crate__api__get_max_timestamp(NativePortType port_);

  external void wire__crate__api__get_waveform_data(NativePortType port_,
      JSAny signal_ids, JSAny? start_time, JSAny? end_time);

  external void wire__crate__api__get_waveform_structure(NativePortType port_);

  external void wire__crate__api__is_waveform_loaded(NativePortType port_);

  external void wire__crate__api__load_waveform(
      NativePortType port_, String file_path);

  external void wire__crate__api__load_waveform_from_bytes(
      NativePortType port_, JSAny bytes, String? file_name);

  external void wire__crate__api__unload_waveform(NativePortType port_);
}
