// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `create_metadata`, `dump_waveform_debug`, `format_signal_value`, `format_to_string`, `load_waveform_native`, `scope_type_to_string`, `timescale_unit_to_string`, `var_type_to_string`
// These types are ignored because they are not used by any `pub` functions: `ScopeInfo`, `WAVEFORM_STATE`, `WaveformState`, `WellenError`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `deref`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `initialize`

/// Load a waveform file (VCD, FST, or GHW) from a file path
///
/// This function parses both the header and body of the waveform file.
/// After calling this, use `get_waveform_structure` to get the hierarchy
/// and `get_waveform_data` to get signal values.
///
/// Note: This function is only available on native platforms (not WASM).
/// For web/WASM, use `load_waveform_from_bytes` instead.
WaveformMetadata loadWaveform({required String filePath}) =>
    RustLib.instance.api.crateApiLoadWaveform(filePath: filePath);

/// Load a waveform from bytes (VCD, FST, or GHW)
///
/// This function parses both the header and body of the waveform from in-memory bytes.
/// This is useful for web/WASM environments where direct file access is not available.
/// After calling this, use `get_waveform_structure` to get the hierarchy
/// and `get_waveform_data` to get signal values.
///
/// # Arguments
/// * `bytes` - The waveform file contents as bytes
/// * `file_name` - Optional filename hint for format detection and metadata
WaveformMetadata loadWaveformFromBytes({
  required List<int> bytes,
  String? fileName,
}) => RustLib.instance.api.crateApiLoadWaveformFromBytes(
  bytes: bytes,
  fileName: fileName,
);

/// Get the waveform structure (hierarchy of modules and signals)
///
/// This returns the complete hierarchy without waveform data.
WaveformStructure getWaveformStructure() =>
    RustLib.instance.api.crateApiGetWaveformStructure();

/// Load waveform data for specific signals
///
/// This loads the actual waveform values for the specified signal IDs.
/// Signal IDs are the full hierarchical paths (e.g., "top.counter.clk").
List<SignalWaveformData> getWaveformData({
  required List<String> signalIds,
  BigInt? startTime,
  BigInt? endTime,
}) => RustLib.instance.api.crateApiGetWaveformData(
  signalIds: signalIds,
  startTime: startTime,
  endTime: endTime,
);

/// Get the maximum timestamp in the waveform
BigInt? getMaxTimestamp() => RustLib.instance.api.crateApiGetMaxTimestamp();

/// Get all timestamps in the waveform
Uint64List getAllTimestamps() =>
    RustLib.instance.api.crateApiGetAllTimestamps();

/// Check if a waveform is currently loaded
bool isWaveformLoaded() => RustLib.instance.api.crateApiIsWaveformLoaded();

/// Unload the current waveform and free resources
void unloadWaveform() => RustLib.instance.api.crateApiUnloadWaveform();

/// Module structure with hierarchy
class ModuleNode {
  final String name;
  final String fullPath;
  final String scopeType;
  final List<SignalInfo> signals;
  final List<ModuleNode> subModules;

  const ModuleNode({
    required this.name,
    required this.fullPath,
    required this.scopeType,
    required this.signals,
    required this.subModules,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      fullPath.hashCode ^
      scopeType.hashCode ^
      signals.hashCode ^
      subModules.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModuleNode &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          fullPath == other.fullPath &&
          scopeType == other.scopeType &&
          signals == other.signals &&
          subModules == other.subModules;
}

/// Information about a signal (variable) in the hierarchy
class SignalInfo {
  final String id;
  final String name;
  final String fullPath;
  final String signalType;
  final int bitWidth;
  final BigInt scopeId;

  const SignalInfo({
    required this.id,
    required this.name,
    required this.fullPath,
    required this.signalType,
    required this.bitWidth,
    required this.scopeId,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      fullPath.hashCode ^
      signalType.hashCode ^
      bitWidth.hashCode ^
      scopeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SignalInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          fullPath == other.fullPath &&
          signalType == other.signalType &&
          bitWidth == other.bitWidth &&
          scopeId == other.scopeId;
}

/// Waveform data for a signal
class SignalWaveformData {
  final String signalId;
  final List<WaveformDataPoint> data;

  const SignalWaveformData({required this.signalId, required this.data});

  @override
  int get hashCode => signalId.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SignalWaveformData &&
          runtimeType == other.runtimeType &&
          signalId == other.signalId &&
          data == other.data;
}

/// A single data point in a waveform
class WaveformDataPoint {
  final BigInt time;
  final String value;

  const WaveformDataPoint({required this.time, required this.value});

  @override
  int get hashCode => time.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WaveformDataPoint &&
          runtimeType == other.runtimeType &&
          time == other.time &&
          value == other.value;
}

/// Metadata about the waveform file
class WaveformMetadata {
  final String source;
  final String timescale;
  final int timescaleFactor;
  final String? date;
  final String? version;
  final String format;
  final BigInt startTime;
  final BigInt endTime;

  const WaveformMetadata({
    required this.source,
    required this.timescale,
    required this.timescaleFactor,
    this.date,
    this.version,
    required this.format,
    required this.startTime,
    required this.endTime,
  });

  @override
  int get hashCode =>
      source.hashCode ^
      timescale.hashCode ^
      timescaleFactor.hashCode ^
      date.hashCode ^
      version.hashCode ^
      format.hashCode ^
      startTime.hashCode ^
      endTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WaveformMetadata &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          timescale == other.timescale &&
          timescaleFactor == other.timescaleFactor &&
          date == other.date &&
          version == other.version &&
          format == other.format &&
          startTime == other.startTime &&
          endTime == other.endTime;
}

/// Complete waveform structure
class WaveformStructure {
  final WaveformMetadata metadata;
  final List<ModuleNode> modules;
  final List<String> allSignalIds;

  const WaveformStructure({
    required this.metadata,
    required this.modules,
    required this.allSignalIds,
  });

  @override
  int get hashCode =>
      metadata.hashCode ^ modules.hashCode ^ allSignalIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WaveformStructure &&
          runtimeType == other.runtimeType &&
          metadata == other.metadata &&
          modules == other.modules &&
          allSignalIds == other.allSignalIds;
}
