// Copyright (C) 2024 Intel Corporation
// SPDX-License-Identifier: BSD-3-Clause
//
// wellen_module_structure_api.dart
// Implementation of ModuleStructureApi using the wellen Rust library via FFI.
//
// 2024 December 30

import 'dart:async';
import 'package:module_structure_api/module_structure_api.dart';

// These types will be generated by flutter_rust_bridge
// For now, we define placeholder types that match the Rust API

/// Placeholder for generated Rust bridge types
/// These will be replaced by auto-generated code from flutter_rust_bridge
class WellenBridge {
  static Future<WaveformMetadataRust> loadWaveform(String filePath) async {
    throw UnimplementedError(
        'Run flutter_rust_bridge_codegen to generate bindings');
  }

  static Future<WaveformStructureRust> getWaveformStructure() async {
    throw UnimplementedError(
        'Run flutter_rust_bridge_codegen to generate bindings');
  }

  static Future<List<SignalWaveformDataRust>> getWaveformData({
    required List<String> signalIds,
    int? startTime,
    int? endTime,
  }) async {
    throw UnimplementedError(
        'Run flutter_rust_bridge_codegen to generate bindings');
  }

  static Future<int?> getMaxTimestamp() async {
    throw UnimplementedError(
        'Run flutter_rust_bridge_codegen to generate bindings');
  }

  static bool isWaveformLoaded() {
    throw UnimplementedError(
        'Run flutter_rust_bridge_codegen to generate bindings');
  }

  static void unloadWaveform() {
    throw UnimplementedError(
        'Run flutter_rust_bridge_codegen to generate bindings');
  }
}

/// Rust bridge type placeholders
class WaveformMetadataRust {
  final String source;
  final String timescale;
  final int timescaleFactor;
  final String? date;
  final String? version;
  final String format;

  WaveformMetadataRust({
    required this.source,
    required this.timescale,
    required this.timescaleFactor,
    this.date,
    this.version,
    required this.format,
  });
}

class WaveformStructureRust {
  final WaveformMetadataRust metadata;
  final List<ModuleNodeRust> modules;
  final List<String> allSignalIds;

  WaveformStructureRust({
    required this.metadata,
    required this.modules,
    required this.allSignalIds,
  });
}

class ModuleNodeRust {
  final String name;
  final String fullPath;
  final String scopeType;
  final List<SignalInfoRust> signals;
  final List<ModuleNodeRust> subModules;

  ModuleNodeRust({
    required this.name,
    required this.fullPath,
    required this.scopeType,
    required this.signals,
    required this.subModules,
  });
}

class SignalInfoRust {
  final String id;
  final String name;
  final String fullPath;
  final String signalType;
  final int bitWidth;
  final int scopeId;

  SignalInfoRust({
    required this.id,
    required this.name,
    required this.fullPath,
    required this.signalType,
    required this.bitWidth,
    required this.scopeId,
  });
}

class SignalWaveformDataRust {
  final String signalId;
  final List<WaveformDataPointRust> data;

  SignalWaveformDataRust({
    required this.signalId,
    required this.data,
  });
}

class WaveformDataPointRust {
  final int time;
  final String value;

  WaveformDataPointRust({
    required this.time,
    required this.value,
  });
}

/// Implementation of ModuleStructureApi using the wellen Rust library.
///
/// This class uses flutter_rust_bridge to call into the wellen library,
/// which can parse VCD, FST, and GHW waveform files.
class WellenModuleStructureApi extends ModuleStructureApi {
  /// The path to the currently loaded waveform file.
  String? _loadedFilePath;

  /// Cached structure after loading
  WaveformStructureRust? _cachedStructure;

  /// All signal IDs from the loaded waveform
  List<String> _allSignalIds = [];

  /// Load a waveform file.
  ///
  /// Supports VCD, FST, and GHW formats.
  Future<void> loadFile(String filePath) async {
    await WellenBridge.loadWaveform(filePath);
    _loadedFilePath = filePath;
    _cachedStructure = await WellenBridge.getWaveformStructure();
    _allSignalIds = _cachedStructure?.allSignalIds ?? [];
  }

  /// Returns the module structure without waveform data.
  @override
  Future<ModuleStructure> getModuleStructure() async {
    if (_cachedStructure == null) {
      return ModuleStructure.empty();
    }

    return _convertToModuleStructure(_cachedStructure!);
  }

  /// Convert Rust structure to Dart ModuleStructure
  ModuleStructure _convertToModuleStructure(WaveformStructureRust rust) {
    return ModuleStructure(
      metadata: MetaData(
        source: rust.metadata.source,
        timescale: rust.metadata.timescale,
        date: rust.metadata.date ?? '',
      ),
      modules: rust.modules.map(_convertModuleNode).toList(),
    );
  }

  /// Convert Rust ModuleNode to Dart Module
  Module _convertModuleNode(ModuleNodeRust rust) {
    return Module(
      name: rust.name,
      subModules: rust.subModules.map(_convertModuleNode).toList(),
      signals: rust.signals.map(_convertSignalInfo).toList(),
    );
  }

  /// Convert Rust SignalInfo to Dart Signal (without data)
  Signal _convertSignalInfo(SignalInfoRust rust) {
    return Signal(
      id: rust.id,
      name: rust.name,
      type: rust.signalType,
      width: rust.bitWidth,
      data: [], // Data loaded separately
    );
  }

  /// Retrieves waveform data for specific signals.
  @override
  Future<List<WaveformData>> getWaveformData({
    required List<String> signalIds,
    int? startTime,
    int? endTime,
  }) async {
    final rustData = await WellenBridge.getWaveformData(
      signalIds: signalIds,
      startTime: startTime,
      endTime: endTime,
    );

    return rustData.map((rust) {
      return WaveformData(
        signalId: rust.signalId,
        data: rust.data.map((point) {
          return Data(time: point.time, value: point.value);
        }).toList(),
      );
    }).toList();
  }

  /// Stream waveform data (loads in chunks for large files)
  @override
  Stream<WaveformData> streamWaveformData({
    required List<String> signalIds,
    int? startTime,
  }) async* {
    // For now, load all at once and yield
    // Future improvement: implement true streaming from Rust
    final allData = await getWaveformData(
      signalIds: signalIds,
      startTime: startTime,
    );

    for (final data in allData) {
      yield data;
    }
  }

  /// Get all signal IDs from the loaded waveform
  List<String> get allSignalIds => _allSignalIds;

  /// Check if a waveform file is currently loaded
  bool get isLoaded => _loadedFilePath != null;

  /// Get the path of the currently loaded file
  String? get loadedFilePath => _loadedFilePath;

  /// Unload the current waveform and free resources
  void unload() {
    WellenBridge.unloadWaveform();
    _loadedFilePath = null;
    _cachedStructure = null;
    _allSignalIds = [];
  }
}
