// Copyright (C) 2025 Intel Corporation
// SPDX-License-Identifier: BSD-3-Clause
//
// wellen_reader.dart
// Wellen-based waveform file reader for VCD, FST, GHW formats.
//
// 2025 Intel Corporation

import 'dart:async';

import 'models/hierarchy.dart';
import 'models/metadata.dart';
import 'models/signal_data.dart';
import 'models/signal_info.dart';
import 'models/wave_format.dart';

// Import the generated Rust FFI bindings
// This file is auto-generated by flutter_rust_bridge
import 'rust/api.dart' as rust_api;
import 'rust/frb_generated.dart';

/// A reader for waveform files using the wellen Rust library.
///
/// This class provides functionality to read VCD, FST, and GHW waveform files.
/// It lazily loads signal data for efficiency, following the same pattern
/// as the surfer wave viewer.
///
/// Example usage:
/// ```dart
/// // Initialize the FFI library (call once at app start)
/// await WellenReader.init();
///
/// final reader = WellenReader();
/// await reader.loadFile('/path/to/waveform.vcd');
///
/// final structure = await reader.getStructure();
/// print('Format: ${structure.metadata.format}');
///
/// final data = await reader.getSignalData(['top.clk', 'top.data']);
/// for (final signal in data) {
///   print('Signal ${signal.signalId}: ${signal.data.length} changes');
/// }
///
/// await reader.close();
/// ```
class WellenReader {
  static bool _initialized = false;

  /// Initialize the Rust FFI library.
  ///
  /// This must be called once before using any WellenReader instances.
  /// It is safe to call multiple times (subsequent calls are no-ops).
  static Future<void> init() async {
    if (!_initialized) {
      await RustLib.init();
      _initialized = true;
    }
  }

  /// Whether a waveform file is currently loaded.
  bool get isLoaded => _isLoaded;
  bool _isLoaded = false;

  /// The metadata of the currently loaded waveform.
  WaveformMetadata? get metadata => _metadata;
  WaveformMetadata? _metadata;

  /// The structure of the currently loaded waveform.
  WaveformStructure? get structure => _structure;
  WaveformStructure? _structure;

  /// Load a waveform file.
  ///
  /// Supports VCD, FST, and GHW formats.
  /// After loading, use [getStructure] to get the hierarchy
  /// and [getSignalData] to get waveform data.
  ///
  /// Throws [WellenException] if the file cannot be loaded.
  Future<WaveformMetadata> loadFile(String filePath) async {
    try {
      final rustMetadata = await rust_api.loadWaveform(filePath: filePath);

      _metadata = WaveformMetadata(
        source: rustMetadata.source,
        timescale: rustMetadata.timescale,
        timescaleFactor: rustMetadata.timescaleFactor,
        date: rustMetadata.date,
        version: rustMetadata.version,
        format: _parseFormat(rustMetadata.format),
      );

      _isLoaded = true;
      return _metadata!;
    } catch (e) {
      throw WellenException('Failed to load waveform: $e');
    }
  }

  /// Get the waveform structure (hierarchy of modules and signals).
  ///
  /// This returns the complete hierarchy without waveform data.
  /// Call [loadFile] first to load a waveform.
  ///
  /// Throws [WellenException] if no waveform is loaded.
  Future<WaveformStructure> getStructure() async {
    if (!_isLoaded) {
      throw WellenException('No waveform loaded');
    }

    if (_structure != null) {
      return _structure!;
    }

    try {
      final rustStructure = await rust_api.getWaveformStructure();

      _structure = WaveformStructure(
        metadata: WaveformMetadata(
          source: rustStructure.metadata.source,
          timescale: rustStructure.metadata.timescale,
          timescaleFactor: rustStructure.metadata.timescaleFactor,
          date: rustStructure.metadata.date,
          version: rustStructure.metadata.version,
          format: _parseFormat(rustStructure.metadata.format),
        ),
        modules: rustStructure.modules.map(_convertModule).toList(),
        allSignalIds: rustStructure.allSignalIds,
      );

      return _structure!;
    } catch (e) {
      throw WellenException('Failed to get waveform structure: $e');
    }
  }

  /// Get waveform data for specific signals.
  ///
  /// [signalIds] - List of signal full paths (e.g., "top.counter.clk").
  /// [startTime] - Optional start time filter.
  /// [endTime] - Optional end time filter.
  ///
  /// Throws [WellenException] if no waveform is loaded or signals not found.
  Future<List<SignalData>> getSignalData(
    List<String> signalIds, {
    int? startTime,
    int? endTime,
  }) async {
    if (!_isLoaded) {
      throw WellenException('No waveform loaded');
    }

    try {
      final rustData = await rust_api.getWaveformData(
        signalIds: signalIds,
        startTime: startTime != null ? BigInt.from(startTime) : null,
        endTime: endTime != null ? BigInt.from(endTime) : null,
      );

      return rustData.map((data) {
        return SignalData(
          signalId: data.signalId,
          data: data.data
              .map((point) => DataPoint(
                    time: point.time.toInt(),
                    value: point.value,
                  ))
              .toList(),
        );
      }).toList();
    } catch (e) {
      throw WellenException('Failed to get waveform data: $e');
    }
  }

  /// Stream waveform data for signals in chunks.
  ///
  /// This is useful for large waveforms where you want to display
  /// data incrementally as it loads.
  ///
  /// [signalIds] - List of signal full paths.
  /// [chunkSize] - Number of signals to load per chunk.
  Stream<List<SignalData>> streamSignalData(
    List<String> signalIds, {
    int chunkSize = 10,
    int? startTime,
    int? endTime,
  }) async* {
    if (!_isLoaded) {
      throw WellenException('No waveform loaded');
    }

    // Split signal IDs into chunks
    for (var i = 0; i < signalIds.length; i += chunkSize) {
      final end =
          (i + chunkSize > signalIds.length) ? signalIds.length : i + chunkSize;
      final chunk = signalIds.sublist(i, end);

      final data = await getSignalData(
        chunk,
        startTime: startTime,
        endTime: endTime,
      );

      yield data;
    }
  }

  /// Get the maximum timestamp in the waveform.
  Future<int?> getMaxTimestamp() async {
    if (!_isLoaded) {
      throw WellenException('No waveform loaded');
    }

    try {
      final result = await rust_api.getMaxTimestamp();
      return result?.toInt();
    } catch (e) {
      throw WellenException('Failed to get max timestamp: $e');
    }
  }

  /// Get all timestamps in the waveform.
  Future<List<int>> getAllTimestamps() async {
    if (!_isLoaded) {
      throw WellenException('No waveform loaded');
    }

    try {
      final result = await rust_api.getAllTimestamps();
      return result.map((t) => t.toInt()).toList();
    } catch (e) {
      throw WellenException('Failed to get timestamps: $e');
    }
  }

  /// Close the reader and release resources.
  Future<void> close() async {
    if (_isLoaded) {
      await rust_api.unloadWaveform();
      _isLoaded = false;
      _metadata = null;
      _structure = null;
    }
  }

  /// Unload the current waveform and release resources (alias for [close]).
  void unload() {
    if (_isLoaded) {
      rust_api.unloadWaveform();
      _isLoaded = false;
      _metadata = null;
      _structure = null;
    }
  }

  /// Get waveform data for specific signals (alias for [getSignalData]).
  Future<List<SignalData>> getWaveformData(
    List<String> signalIds, {
    int? startTime,
    int? endTime,
  }) =>
      getSignalData(signalIds, startTime: startTime, endTime: endTime);

  /// Parse wave format from string.
  WaveFormat _parseFormat(String format) {
    switch (format.toUpperCase()) {
      case 'VCD':
        return WaveFormat.vcd;
      case 'FST':
        return WaveFormat.fst;
      case 'GHW':
        return WaveFormat.ghw;
      default:
        return WaveFormat.unknown;
    }
  }

  /// Convert Rust module node to Dart.
  ModuleNode _convertModule(rust_api.ModuleNode rustNode) {
    return ModuleNode(
      name: rustNode.name,
      fullPath: rustNode.fullPath,
      scopeType: rustNode.scopeType,
      signals: rustNode.signals.map(_convertSignal).toList(),
      subModules: rustNode.subModules.map(_convertModule).toList(),
    );
  }

  /// Convert Rust signal info to Dart.
  SignalInfo _convertSignal(rust_api.SignalInfo rustSignal) {
    return SignalInfo(
      id: rustSignal.id,
      name: rustSignal.name,
      fullPath: rustSignal.fullPath,
      signalType: rustSignal.signalType,
      bitWidth: rustSignal.bitWidth,
      scopeId: rustSignal.scopeId.toInt(),
    );
  }
}

/// Exception thrown by WellenReader operations.
class WellenException implements Exception {
  /// Creates a new WellenException with the given message.
  WellenException(this.message);

  /// The error message.
  final String message;

  @override
  String toString() => 'WellenException: $message';
}
