// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = DcoCodec,
    default_rust_opaque = RustOpaqueNom,
    default_rust_auto_opaque = RustAutoOpaqueNom,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.7.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 1646248376;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__get_all_timestamps_impl(
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_all_timestamps",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            transform_result_dco::<_, _, String>((move || {
                let output_ok = crate::api::get_all_timestamps()?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__get_max_timestamp_impl(
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_max_timestamp",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            transform_result_dco::<_, _, String>((move || {
                let output_ok = crate::api::get_max_timestamp()?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__get_waveform_data_impl(
    signal_ids: impl CstDecode<Vec<String>>,
    start_time: impl CstDecode<Option<u64>>,
    end_time: impl CstDecode<Option<u64>>,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_waveform_data",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let api_signal_ids = signal_ids.cst_decode();
            let api_start_time = start_time.cst_decode();
            let api_end_time = end_time.cst_decode();
            transform_result_dco::<_, _, String>((move || {
                let output_ok =
                    crate::api::get_waveform_data(api_signal_ids, api_start_time, api_end_time)?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__get_waveform_structure_impl(
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_waveform_structure",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            transform_result_dco::<_, _, String>((move || {
                let output_ok = crate::api::get_waveform_structure()?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__is_waveform_loaded_impl(
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "is_waveform_loaded",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            transform_result_dco::<_, _, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::is_waveform_loaded())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__load_waveform_impl(
    _file_path: impl CstDecode<String>,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "load_waveform",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let api__file_path = _file_path.cst_decode();
            transform_result_dco::<_, _, String>((move || {
                let output_ok = crate::api::load_waveform(api__file_path)?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__load_waveform_from_bytes_impl(
    bytes: impl CstDecode<Vec<u8>>,
    file_name: impl CstDecode<Option<String>>,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "load_waveform_from_bytes",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let api_bytes = bytes.cst_decode();
            let api_file_name = file_name.cst_decode();
            transform_result_dco::<_, _, String>((move || {
                let output_ok = crate::api::load_waveform_from_bytes(api_bytes, api_file_name)?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__unload_waveform_impl(
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "unload_waveform",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            transform_result_dco::<_, _, ()>((move || {
                let output_ok = Result::<_, ()>::Ok({
                    crate::api::unload_waveform();
                })?;
                Ok(output_ok)
            })())
        },
    )
}

// Section: dart2rust

impl CstDecode<bool> for bool {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> bool {
        self
    }
}
impl CstDecode<u32> for u32 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> u32 {
        self
    }
}
impl CstDecode<u64> for u64 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> u64 {
        self
    }
}
impl CstDecode<u8> for u8 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> u8 {
        self
    }
}
impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::ModuleNode> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::ModuleNode>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u64>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::SignalInfo> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::SignalInfo>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::SignalWaveformData> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::SignalWaveformData>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::WaveformDataPoint> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::WaveformDataPoint>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::ModuleNode {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_fullPath = <String>::sse_decode(deserializer);
        let mut var_scopeType = <String>::sse_decode(deserializer);
        let mut var_signals = <Vec<crate::api::SignalInfo>>::sse_decode(deserializer);
        let mut var_subModules = <Vec<crate::api::ModuleNode>>::sse_decode(deserializer);
        return crate::api::ModuleNode {
            name: var_name,
            full_path: var_fullPath,
            scope_type: var_scopeType,
            signals: var_signals,
            sub_modules: var_subModules,
        };
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::SignalInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_fullPath = <String>::sse_decode(deserializer);
        let mut var_signalType = <String>::sse_decode(deserializer);
        let mut var_bitWidth = <u32>::sse_decode(deserializer);
        let mut var_scopeId = <u64>::sse_decode(deserializer);
        return crate::api::SignalInfo {
            id: var_id,
            name: var_name,
            full_path: var_fullPath,
            signal_type: var_signalType,
            bit_width: var_bitWidth,
            scope_id: var_scopeId,
        };
    }
}

impl SseDecode for crate::api::SignalWaveformData {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_signalId = <String>::sse_decode(deserializer);
        let mut var_data = <Vec<crate::api::WaveformDataPoint>>::sse_decode(deserializer);
        return crate::api::SignalWaveformData {
            signal_id: var_signalId,
            data: var_data,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for crate::api::WaveformDataPoint {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_time = <u64>::sse_decode(deserializer);
        let mut var_value = <String>::sse_decode(deserializer);
        return crate::api::WaveformDataPoint {
            time: var_time,
            value: var_value,
        };
    }
}

impl SseDecode for crate::api::WaveformMetadata {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_source = <String>::sse_decode(deserializer);
        let mut var_timescale = <String>::sse_decode(deserializer);
        let mut var_timescaleFactor = <u32>::sse_decode(deserializer);
        let mut var_date = <Option<String>>::sse_decode(deserializer);
        let mut var_version = <Option<String>>::sse_decode(deserializer);
        let mut var_format = <String>::sse_decode(deserializer);
        let mut var_startTime = <u64>::sse_decode(deserializer);
        let mut var_endTime = <u64>::sse_decode(deserializer);
        return crate::api::WaveformMetadata {
            source: var_source,
            timescale: var_timescale,
            timescale_factor: var_timescaleFactor,
            date: var_date,
            version: var_version,
            format: var_format,
            start_time: var_startTime,
            end_time: var_endTime,
        };
    }
}

impl SseDecode for crate::api::WaveformStructure {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_metadata = <crate::api::WaveformMetadata>::sse_decode(deserializer);
        let mut var_modules = <Vec<crate::api::ModuleNode>>::sse_decode(deserializer);
        let mut var_allSignalIds = <Vec<String>>::sse_decode(deserializer);
        return crate::api::WaveformStructure {
            metadata: var_metadata,
            modules: var_modules,
            all_signal_ids: var_allSignalIds,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::ModuleNode {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.name.into_into_dart().into_dart(),
            self.full_path.into_into_dart().into_dart(),
            self.scope_type.into_into_dart().into_dart(),
            self.signals.into_into_dart().into_dart(),
            self.sub_modules.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::ModuleNode {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::ModuleNode> for crate::api::ModuleNode {
    fn into_into_dart(self) -> crate::api::ModuleNode {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::SignalInfo {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.full_path.into_into_dart().into_dart(),
            self.signal_type.into_into_dart().into_dart(),
            self.bit_width.into_into_dart().into_dart(),
            self.scope_id.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::SignalInfo {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::SignalInfo> for crate::api::SignalInfo {
    fn into_into_dart(self) -> crate::api::SignalInfo {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::SignalWaveformData {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.signal_id.into_into_dart().into_dart(),
            self.data.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::SignalWaveformData
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::SignalWaveformData>
    for crate::api::SignalWaveformData
{
    fn into_into_dart(self) -> crate::api::SignalWaveformData {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::WaveformDataPoint {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.time.into_into_dart().into_dart(),
            self.value.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::WaveformDataPoint {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::WaveformDataPoint>
    for crate::api::WaveformDataPoint
{
    fn into_into_dart(self) -> crate::api::WaveformDataPoint {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::WaveformMetadata {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.source.into_into_dart().into_dart(),
            self.timescale.into_into_dart().into_dart(),
            self.timescale_factor.into_into_dart().into_dart(),
            self.date.into_into_dart().into_dart(),
            self.version.into_into_dart().into_dart(),
            self.format.into_into_dart().into_dart(),
            self.start_time.into_into_dart().into_dart(),
            self.end_time.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::WaveformMetadata {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::WaveformMetadata>
    for crate::api::WaveformMetadata
{
    fn into_into_dart(self) -> crate::api::WaveformMetadata {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::WaveformStructure {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.metadata.into_into_dart().into_dart(),
            self.modules.into_into_dart().into_dart(),
            self.all_signal_ids.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::WaveformStructure {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::WaveformStructure>
    for crate::api::WaveformStructure
{
    fn into_into_dart(self) -> crate::api::WaveformStructure {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::ModuleNode> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::ModuleNode>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u64>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::SignalInfo> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::SignalInfo>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::SignalWaveformData> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::SignalWaveformData>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::WaveformDataPoint> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::WaveformDataPoint>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::ModuleNode {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.name, serializer);
        <String>::sse_encode(self.full_path, serializer);
        <String>::sse_encode(self.scope_type, serializer);
        <Vec<crate::api::SignalInfo>>::sse_encode(self.signals, serializer);
        <Vec<crate::api::ModuleNode>>::sse_encode(self.sub_modules, serializer);
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::SignalInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.name, serializer);
        <String>::sse_encode(self.full_path, serializer);
        <String>::sse_encode(self.signal_type, serializer);
        <u32>::sse_encode(self.bit_width, serializer);
        <u64>::sse_encode(self.scope_id, serializer);
    }
}

impl SseEncode for crate::api::SignalWaveformData {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.signal_id, serializer);
        <Vec<crate::api::WaveformDataPoint>>::sse_encode(self.data, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for crate::api::WaveformDataPoint {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.time, serializer);
        <String>::sse_encode(self.value, serializer);
    }
}

impl SseEncode for crate::api::WaveformMetadata {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.source, serializer);
        <String>::sse_encode(self.timescale, serializer);
        <u32>::sse_encode(self.timescale_factor, serializer);
        <Option<String>>::sse_encode(self.date, serializer);
        <Option<String>>::sse_encode(self.version, serializer);
        <String>::sse_encode(self.format, serializer);
        <u64>::sse_encode(self.start_time, serializer);
        <u64>::sse_encode(self.end_time, serializer);
    }
}

impl SseEncode for crate::api::WaveformStructure {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::WaveformMetadata>::sse_encode(self.metadata, serializer);
        <Vec<crate::api::ModuleNode>>::sse_encode(self.modules, serializer);
        <Vec<String>>::sse_encode(self.all_signal_ids, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.7.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();

    // Section: dart2rust

    impl CstDecode<String> for *mut wire_cst_list_prim_u_8_strict {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> String {
            let vec: Vec<u8> = self.cst_decode();
            String::from_utf8(vec).unwrap()
        }
    }
    impl CstDecode<u64> for *mut u64 {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> u64 {
            unsafe { *flutter_rust_bridge::for_generated::box_from_leak_ptr(self) }
        }
    }
    impl CstDecode<Vec<String>> for *mut wire_cst_list_String {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<String> {
            let vec = unsafe {
                let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
            };
            vec.into_iter().map(CstDecode::cst_decode).collect()
        }
    }
    impl CstDecode<Vec<crate::api::ModuleNode>> for *mut wire_cst_list_module_node {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<crate::api::ModuleNode> {
            let vec = unsafe {
                let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
            };
            vec.into_iter().map(CstDecode::cst_decode).collect()
        }
    }
    impl CstDecode<Vec<u64>> for *mut wire_cst_list_prim_u_64_strict {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<u64> {
            unsafe {
                let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
            }
        }
    }
    impl CstDecode<Vec<u8>> for *mut wire_cst_list_prim_u_8_loose {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<u8> {
            unsafe {
                let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
            }
        }
    }
    impl CstDecode<Vec<u8>> for *mut wire_cst_list_prim_u_8_strict {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<u8> {
            unsafe {
                let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
            }
        }
    }
    impl CstDecode<Vec<crate::api::SignalInfo>> for *mut wire_cst_list_signal_info {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<crate::api::SignalInfo> {
            let vec = unsafe {
                let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
            };
            vec.into_iter().map(CstDecode::cst_decode).collect()
        }
    }
    impl CstDecode<Vec<crate::api::SignalWaveformData>> for *mut wire_cst_list_signal_waveform_data {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<crate::api::SignalWaveformData> {
            let vec = unsafe {
                let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
            };
            vec.into_iter().map(CstDecode::cst_decode).collect()
        }
    }
    impl CstDecode<Vec<crate::api::WaveformDataPoint>> for *mut wire_cst_list_waveform_data_point {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<crate::api::WaveformDataPoint> {
            let vec = unsafe {
                let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
            };
            vec.into_iter().map(CstDecode::cst_decode).collect()
        }
    }
    impl CstDecode<crate::api::ModuleNode> for wire_cst_module_node {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::ModuleNode {
            crate::api::ModuleNode {
                name: self.name.cst_decode(),
                full_path: self.full_path.cst_decode(),
                scope_type: self.scope_type.cst_decode(),
                signals: self.signals.cst_decode(),
                sub_modules: self.sub_modules.cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::SignalInfo> for wire_cst_signal_info {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::SignalInfo {
            crate::api::SignalInfo {
                id: self.id.cst_decode(),
                name: self.name.cst_decode(),
                full_path: self.full_path.cst_decode(),
                signal_type: self.signal_type.cst_decode(),
                bit_width: self.bit_width.cst_decode(),
                scope_id: self.scope_id.cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::SignalWaveformData> for wire_cst_signal_waveform_data {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::SignalWaveformData {
            crate::api::SignalWaveformData {
                signal_id: self.signal_id.cst_decode(),
                data: self.data.cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::WaveformDataPoint> for wire_cst_waveform_data_point {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::WaveformDataPoint {
            crate::api::WaveformDataPoint {
                time: self.time.cst_decode(),
                value: self.value.cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::WaveformMetadata> for wire_cst_waveform_metadata {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::WaveformMetadata {
            crate::api::WaveformMetadata {
                source: self.source.cst_decode(),
                timescale: self.timescale.cst_decode(),
                timescale_factor: self.timescale_factor.cst_decode(),
                date: self.date.cst_decode(),
                version: self.version.cst_decode(),
                format: self.format.cst_decode(),
                start_time: self.start_time.cst_decode(),
                end_time: self.end_time.cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::WaveformStructure> for wire_cst_waveform_structure {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::WaveformStructure {
            crate::api::WaveformStructure {
                metadata: self.metadata.cst_decode(),
                modules: self.modules.cst_decode(),
                all_signal_ids: self.all_signal_ids.cst_decode(),
            }
        }
    }
    impl NewWithNullPtr for wire_cst_module_node {
        fn new_with_null_ptr() -> Self {
            Self {
                name: core::ptr::null_mut(),
                full_path: core::ptr::null_mut(),
                scope_type: core::ptr::null_mut(),
                signals: core::ptr::null_mut(),
                sub_modules: core::ptr::null_mut(),
            }
        }
    }
    impl Default for wire_cst_module_node {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_signal_info {
        fn new_with_null_ptr() -> Self {
            Self {
                id: core::ptr::null_mut(),
                name: core::ptr::null_mut(),
                full_path: core::ptr::null_mut(),
                signal_type: core::ptr::null_mut(),
                bit_width: Default::default(),
                scope_id: Default::default(),
            }
        }
    }
    impl Default for wire_cst_signal_info {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_signal_waveform_data {
        fn new_with_null_ptr() -> Self {
            Self {
                signal_id: core::ptr::null_mut(),
                data: core::ptr::null_mut(),
            }
        }
    }
    impl Default for wire_cst_signal_waveform_data {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_waveform_data_point {
        fn new_with_null_ptr() -> Self {
            Self {
                time: Default::default(),
                value: core::ptr::null_mut(),
            }
        }
    }
    impl Default for wire_cst_waveform_data_point {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_waveform_metadata {
        fn new_with_null_ptr() -> Self {
            Self {
                source: core::ptr::null_mut(),
                timescale: core::ptr::null_mut(),
                timescale_factor: Default::default(),
                date: core::ptr::null_mut(),
                version: core::ptr::null_mut(),
                format: core::ptr::null_mut(),
                start_time: Default::default(),
                end_time: Default::default(),
            }
        }
    }
    impl Default for wire_cst_waveform_metadata {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_waveform_structure {
        fn new_with_null_ptr() -> Self {
            Self {
                metadata: Default::default(),
                modules: core::ptr::null_mut(),
                all_signal_ids: core::ptr::null_mut(),
            }
        }
    }
    impl Default for wire_cst_waveform_structure {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }

    #[no_mangle]
    pub extern "C" fn frbgen_rohd_wellen_wire__crate__api__get_all_timestamps(
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__get_all_timestamps_impl()
    }

    #[no_mangle]
    pub extern "C" fn frbgen_rohd_wellen_wire__crate__api__get_max_timestamp(
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__get_max_timestamp_impl()
    }

    #[no_mangle]
    pub extern "C" fn frbgen_rohd_wellen_wire__crate__api__get_waveform_data(
        signal_ids: *mut wire_cst_list_String,
        start_time: *mut u64,
        end_time: *mut u64,
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__get_waveform_data_impl(signal_ids, start_time, end_time)
    }

    #[no_mangle]
    pub extern "C" fn frbgen_rohd_wellen_wire__crate__api__get_waveform_structure(
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__get_waveform_structure_impl()
    }

    #[no_mangle]
    pub extern "C" fn frbgen_rohd_wellen_wire__crate__api__is_waveform_loaded(
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__is_waveform_loaded_impl()
    }

    #[no_mangle]
    pub extern "C" fn frbgen_rohd_wellen_wire__crate__api__load_waveform(
        _file_path: *mut wire_cst_list_prim_u_8_strict,
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__load_waveform_impl(_file_path)
    }

    #[no_mangle]
    pub extern "C" fn frbgen_rohd_wellen_wire__crate__api__load_waveform_from_bytes(
        bytes: *mut wire_cst_list_prim_u_8_loose,
        file_name: *mut wire_cst_list_prim_u_8_strict,
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__load_waveform_from_bytes_impl(bytes, file_name)
    }

    #[no_mangle]
    pub extern "C" fn frbgen_rohd_wellen_wire__crate__api__unload_waveform(
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__unload_waveform_impl()
    }

    #[no_mangle]
    pub extern "C" fn frbgen_rohd_wellen_cst_new_box_autoadd_u_64(value: u64) -> *mut u64 {
        flutter_rust_bridge::for_generated::new_leak_box_ptr(value)
    }

    #[no_mangle]
    pub extern "C" fn frbgen_rohd_wellen_cst_new_list_String(
        len: i32,
    ) -> *mut wire_cst_list_String {
        let wrap = wire_cst_list_String {
            ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(
                <*mut wire_cst_list_prim_u_8_strict>::new_with_null_ptr(),
                len,
            ),
            len,
        };
        flutter_rust_bridge::for_generated::new_leak_box_ptr(wrap)
    }

    #[no_mangle]
    pub extern "C" fn frbgen_rohd_wellen_cst_new_list_module_node(
        len: i32,
    ) -> *mut wire_cst_list_module_node {
        let wrap = wire_cst_list_module_node {
            ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(
                <wire_cst_module_node>::new_with_null_ptr(),
                len,
            ),
            len,
        };
        flutter_rust_bridge::for_generated::new_leak_box_ptr(wrap)
    }

    #[no_mangle]
    pub extern "C" fn frbgen_rohd_wellen_cst_new_list_prim_u_64_strict(
        len: i32,
    ) -> *mut wire_cst_list_prim_u_64_strict {
        let ans = wire_cst_list_prim_u_64_strict {
            ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(Default::default(), len),
            len,
        };
        flutter_rust_bridge::for_generated::new_leak_box_ptr(ans)
    }

    #[no_mangle]
    pub extern "C" fn frbgen_rohd_wellen_cst_new_list_prim_u_8_loose(
        len: i32,
    ) -> *mut wire_cst_list_prim_u_8_loose {
        let ans = wire_cst_list_prim_u_8_loose {
            ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(Default::default(), len),
            len,
        };
        flutter_rust_bridge::for_generated::new_leak_box_ptr(ans)
    }

    #[no_mangle]
    pub extern "C" fn frbgen_rohd_wellen_cst_new_list_prim_u_8_strict(
        len: i32,
    ) -> *mut wire_cst_list_prim_u_8_strict {
        let ans = wire_cst_list_prim_u_8_strict {
            ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(Default::default(), len),
            len,
        };
        flutter_rust_bridge::for_generated::new_leak_box_ptr(ans)
    }

    #[no_mangle]
    pub extern "C" fn frbgen_rohd_wellen_cst_new_list_signal_info(
        len: i32,
    ) -> *mut wire_cst_list_signal_info {
        let wrap = wire_cst_list_signal_info {
            ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(
                <wire_cst_signal_info>::new_with_null_ptr(),
                len,
            ),
            len,
        };
        flutter_rust_bridge::for_generated::new_leak_box_ptr(wrap)
    }

    #[no_mangle]
    pub extern "C" fn frbgen_rohd_wellen_cst_new_list_signal_waveform_data(
        len: i32,
    ) -> *mut wire_cst_list_signal_waveform_data {
        let wrap = wire_cst_list_signal_waveform_data {
            ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(
                <wire_cst_signal_waveform_data>::new_with_null_ptr(),
                len,
            ),
            len,
        };
        flutter_rust_bridge::for_generated::new_leak_box_ptr(wrap)
    }

    #[no_mangle]
    pub extern "C" fn frbgen_rohd_wellen_cst_new_list_waveform_data_point(
        len: i32,
    ) -> *mut wire_cst_list_waveform_data_point {
        let wrap = wire_cst_list_waveform_data_point {
            ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(
                <wire_cst_waveform_data_point>::new_with_null_ptr(),
                len,
            ),
            len,
        };
        flutter_rust_bridge::for_generated::new_leak_box_ptr(wrap)
    }

    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_list_String {
        ptr: *mut *mut wire_cst_list_prim_u_8_strict,
        len: i32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_list_module_node {
        ptr: *mut wire_cst_module_node,
        len: i32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_list_prim_u_64_strict {
        ptr: *mut u64,
        len: i32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_list_prim_u_8_loose {
        ptr: *mut u8,
        len: i32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_list_prim_u_8_strict {
        ptr: *mut u8,
        len: i32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_list_signal_info {
        ptr: *mut wire_cst_signal_info,
        len: i32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_list_signal_waveform_data {
        ptr: *mut wire_cst_signal_waveform_data,
        len: i32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_list_waveform_data_point {
        ptr: *mut wire_cst_waveform_data_point,
        len: i32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_module_node {
        name: *mut wire_cst_list_prim_u_8_strict,
        full_path: *mut wire_cst_list_prim_u_8_strict,
        scope_type: *mut wire_cst_list_prim_u_8_strict,
        signals: *mut wire_cst_list_signal_info,
        sub_modules: *mut wire_cst_list_module_node,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_signal_info {
        id: *mut wire_cst_list_prim_u_8_strict,
        name: *mut wire_cst_list_prim_u_8_strict,
        full_path: *mut wire_cst_list_prim_u_8_strict,
        signal_type: *mut wire_cst_list_prim_u_8_strict,
        bit_width: u32,
        scope_id: u64,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_signal_waveform_data {
        signal_id: *mut wire_cst_list_prim_u_8_strict,
        data: *mut wire_cst_list_waveform_data_point,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_waveform_data_point {
        time: u64,
        value: *mut wire_cst_list_prim_u_8_strict,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_waveform_metadata {
        source: *mut wire_cst_list_prim_u_8_strict,
        timescale: *mut wire_cst_list_prim_u_8_strict,
        timescale_factor: u32,
        date: *mut wire_cst_list_prim_u_8_strict,
        version: *mut wire_cst_list_prim_u_8_strict,
        format: *mut wire_cst_list_prim_u_8_strict,
        start_time: u64,
        end_time: u64,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_waveform_structure {
        metadata: wire_cst_waveform_metadata,
        modules: *mut wire_cst_list_module_node,
        all_signal_ids: *mut wire_cst_list_String,
    }
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.7.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();

    // Section: dart2rust

    impl CstDecode<String> for String {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> String {
            self
        }
    }
    impl CstDecode<Vec<String>> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<String> {
            self.dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap()
                .iter()
                .map(CstDecode::cst_decode)
                .collect()
        }
    }
    impl CstDecode<Vec<crate::api::ModuleNode>>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<crate::api::ModuleNode> {
            self.dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap()
                .iter()
                .map(CstDecode::cst_decode)
                .collect()
        }
    }
    impl CstDecode<Vec<u64>> for Box<[u64]> {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<u64> {
            self.into_vec()
        }
    }
    impl CstDecode<Vec<u8>> for Box<[u8]> {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<u8> {
            self.into_vec()
        }
    }
    impl CstDecode<Vec<crate::api::SignalInfo>>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<crate::api::SignalInfo> {
            self.dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap()
                .iter()
                .map(CstDecode::cst_decode)
                .collect()
        }
    }
    impl CstDecode<Vec<crate::api::SignalWaveformData>>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<crate::api::SignalWaveformData> {
            self.dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap()
                .iter()
                .map(CstDecode::cst_decode)
                .collect()
        }
    }
    impl CstDecode<Vec<crate::api::WaveformDataPoint>>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<crate::api::WaveformDataPoint> {
            self.dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap()
                .iter()
                .map(CstDecode::cst_decode)
                .collect()
        }
    }
    impl CstDecode<crate::api::ModuleNode>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::ModuleNode {
            let self_ = self
                .dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap();
            assert_eq!(
                self_.length(),
                5,
                "Expected 5 elements, got {}",
                self_.length()
            );
            crate::api::ModuleNode {
                name: self_.get(0).cst_decode(),
                full_path: self_.get(1).cst_decode(),
                scope_type: self_.get(2).cst_decode(),
                signals: self_.get(3).cst_decode(),
                sub_modules: self_.get(4).cst_decode(),
            }
        }
    }
    impl CstDecode<Option<String>> for Option<String> {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Option<String> {
            self.map(CstDecode::cst_decode)
        }
    }
    impl CstDecode<crate::api::SignalInfo>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::SignalInfo {
            let self_ = self
                .dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap();
            assert_eq!(
                self_.length(),
                6,
                "Expected 6 elements, got {}",
                self_.length()
            );
            crate::api::SignalInfo {
                id: self_.get(0).cst_decode(),
                name: self_.get(1).cst_decode(),
                full_path: self_.get(2).cst_decode(),
                signal_type: self_.get(3).cst_decode(),
                bit_width: self_.get(4).cst_decode(),
                scope_id: self_.get(5).cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::SignalWaveformData>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::SignalWaveformData {
            let self_ = self
                .dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap();
            assert_eq!(
                self_.length(),
                2,
                "Expected 2 elements, got {}",
                self_.length()
            );
            crate::api::SignalWaveformData {
                signal_id: self_.get(0).cst_decode(),
                data: self_.get(1).cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::WaveformDataPoint>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::WaveformDataPoint {
            let self_ = self
                .dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap();
            assert_eq!(
                self_.length(),
                2,
                "Expected 2 elements, got {}",
                self_.length()
            );
            crate::api::WaveformDataPoint {
                time: self_.get(0).cst_decode(),
                value: self_.get(1).cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::WaveformMetadata>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::WaveformMetadata {
            let self_ = self
                .dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap();
            assert_eq!(
                self_.length(),
                8,
                "Expected 8 elements, got {}",
                self_.length()
            );
            crate::api::WaveformMetadata {
                source: self_.get(0).cst_decode(),
                timescale: self_.get(1).cst_decode(),
                timescale_factor: self_.get(2).cst_decode(),
                date: self_.get(3).cst_decode(),
                version: self_.get(4).cst_decode(),
                format: self_.get(5).cst_decode(),
                start_time: self_.get(6).cst_decode(),
                end_time: self_.get(7).cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::WaveformStructure>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::WaveformStructure {
            let self_ = self
                .dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap();
            assert_eq!(
                self_.length(),
                3,
                "Expected 3 elements, got {}",
                self_.length()
            );
            crate::api::WaveformStructure {
                metadata: self_.get(0).cst_decode(),
                modules: self_.get(1).cst_decode(),
                all_signal_ids: self_.get(2).cst_decode(),
            }
        }
    }
    impl CstDecode<String> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> String {
            self.as_string().expect("non-UTF-8 string, or not a string")
        }
    }
    impl CstDecode<bool> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> bool {
            self.is_truthy()
        }
    }
    impl CstDecode<Vec<u64>> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<u64> {
            let buf = self
                .dyn_into::<flutter_rust_bridge::for_generated::js_sys::BigUint64Array>()
                .unwrap();
            let buf = flutter_rust_bridge::for_generated::js_sys::Uint8Array::new(&buf.buffer());
            flutter_rust_bridge::for_generated::slice_from_byte_buffer(buf.to_vec()).into()
        }
    }
    impl CstDecode<Vec<u8>> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<u8> {
            self.unchecked_into::<flutter_rust_bridge::for_generated::js_sys::Uint8Array>()
                .to_vec()
                .into()
        }
    }
    impl CstDecode<u32> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> u32 {
            self.unchecked_into_f64() as _
        }
    }
    impl CstDecode<u64> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> u64 {
            ::std::convert::TryInto::<u64>::try_into(self).unwrap() as _
        }
    }
    impl CstDecode<u8> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> u8 {
            self.unchecked_into_f64() as _
        }
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__get_all_timestamps(
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__get_all_timestamps_impl()
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__get_max_timestamp(
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__get_max_timestamp_impl()
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__get_waveform_data(
        signal_ids: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
        start_time: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
        end_time: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__get_waveform_data_impl(signal_ids, start_time, end_time)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__get_waveform_structure(
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__get_waveform_structure_impl()
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__is_waveform_loaded(
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__is_waveform_loaded_impl()
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__load_waveform(
        _file_path: String,
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__load_waveform_impl(_file_path)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__load_waveform_from_bytes(
        bytes: Box<[u8]>,
        file_name: Option<String>,
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__load_waveform_from_bytes_impl(bytes, file_name)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__unload_waveform(
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__unload_waveform_impl()
    }
}
#[cfg(target_family = "wasm")]
pub use web::*;
